inicio
    variavel inteiro caso_escolhe
    escrever "Digite 1 para começar a bater papo", "\nDigite 2 para sair", "\nDigite 3 para dizer 'não estou afim de bater papo'"
    ler caso_escolhe
    escolhe ( caso_escolhe )
        caso 1:
            escrever "\nOlá!"
        caso 2:
            escrever "\nTchau!"
        caso 3:
            escrever "\nNem eu!"
        defeito:
            escrever "Esta não é uma opção válida!"
    fimescolhe
fim

